# Generated by Django 3.0.4 on 2020-03-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_serials', '0003_auto_20200306_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='serial_id',
            field=models.IntegerField(max_length=50),
        ),
    ]
