# Generated by Django 3.0.4 on 2020-03-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_serials', '0004_auto_20200306_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='serial_id',
            field=models.IntegerField(),
        ),
    ]
