# Generated by Django 3.0.4 on 2020-03-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_serials', '0006_auto_20200316_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='air_date',
            field=models.CharField(max_length=50),
        ),
    ]
