# Generated by Django 3.0.4 on 2020-03-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_serials', '0007_auto_20200316_1348'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='serial',
            constraint=models.UniqueConstraint(fields=('serial_id', 'owner'), name='unique_serial_for_user'),
        ),
    ]
