# Generated by Django 3.0.4 on 2020-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_serials', '0009_remove_serial_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='air_date',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
