# Generated by Django 3.0.4 on 2020-03-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_serials', '0011_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
