# Generated by Django 3.0.4 on 2020-03-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_serials', '0012_auto_20200322_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='air_date',
            field=models.CharField(default='N/A', max_length=4),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
